### ISSUE TITLE
Code difference with x-cube-tcpp

### ISSUE THREAD

**Issue by davedesro** [STMicroelectronics/stm32-mw-usbpd-device-g0#1]
Which one should we use? This one or the code here? https://github.com/STMicroelectronics/x-cube-tcpp/tree/main/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX

There are slight differences. 

Please advise.

**Comment by HFISTM** [comment]
Hello @davedesro and sorry for the late reply.

The device component you pointed at in x-cube-tcpp is version v3.5.0, as can be seen in the release notes.
The version in this repo when you opened the ticket was out of date (v3.4.1).

I just pushed v3.5.0 and v3.5.1, **you can use [v3.5.1](https://github.com/STMicroelectronics/stm32-mw-usbpd-device-g0/releases/tag/v3.5.1) for the most up to date**.
Thanks for pointing out this misalignment issue.

Regards

**Comment by davedesro** [comment]
Thankyou @HFISTM
