### ISSUE TITLE
USBPD source power negotiation

### ISSUE THREAD

**Issue by zx-zx-zx** [STMicroelectronics/stm32-mw-usbpd-device-g0#2]
I tried to port USBPD on H5, but I encountered a problem. Every time the sink is plugged in, the source will only broadcast once, and there is no rolling transmission multiple times.

![image](https://github.com/STMicroelectronics/stm32-mw-usbpd-device-g0/assets/54627541/c7c3f0c7-a1bd-42d1-8d1d-edd0865ce5d6)

I compared the complete PD charger and it can perform multiple broadcasts. How should I debug this problem?
![image](https://github.com/STMicroelectronics/stm32-mw-usbpd-device-g0/assets/54627541/b099c803-4ee3-4b14-8112-3cc3ece16025)

**Comment by HFISTM** [comment]
Hello @zx-zx-zx 

Thank you for your question.

You are posting this issue on the repository related only to the Device part of the USBPD middleware, for STM32G0. I'm not sure it is the right place to relate your application related issue on STM32H5.

For H5, please find some USBPD examples in the STM32CubeH5 repo:
- [Source application](https://github.com/STMicroelectronics/STM32CubeH5/tree/main/Projects/STM32H573I-DK/Applications/USBPD/USBPD_SRC)
- [Sink application](https://github.com/STMicroelectronics/STM32CubeH5/tree/main/Projects/NUCLEO-H563ZI/Applications/USBPD/USBPD_SNK)

I am sorry but can't really help with your issue from the info given.
What MCU are you using ? What application did you try to "port" ? Is your device a sink or a source ?
In the trace, what is the Source ? What is the "complete PD charger" ?
Where is this trace coming from - your device or another ?

Thanks you & best regards

**Comment by ALABSTM** [comment]
Hi @zx-zx-zx,

Please allow us to close this issue as no feedback provided with the requested information. Do not hesitate to log another issue if the problem still persists. Thank you for your comprehension.

With regards,
